### ISSUE TITLE
Failed to get account profile/token

### ISSUE THREAD

**Issue by nikotidar** [ardzz/spotify-converter#1]
Berikut adalah pesan error yang di tampilkan

![Error](https://i.imgur.com/dgkOJ3Z.png)

Saya menggunakan Archlinux dengan php 7.3.4, berikut adalah outputnya

```
PHP 7.3.4 (cli) (built: Apr  5 2019 12:40:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.4, Copyright (c) 1998-2018 Zend Technologies
```
Dan module Curl pada PHP juga sudah saya aktifkan.

**Comment by ardzz** [comment]
Mohon maaf atas ketidaknyamanan saya baru buka github, insyaAllah akan saya perbaiki

**Comment by ardzz** [comment]
Sebelumnya mas pake IP Indonesia?

**Comment by ardzz** [comment]
Soalnya nanti kirim request ke `https://accounts.spotify.com/login/?_locale=id-ID` dan kemungkinan kalau IP nya bukan dari Indonesia otomatis redirect

**Comment by ardzz** [comment]
![Screenshot from 2019-05-17 14-35-20](https://user-images.githubusercontent.com/38525912/57911239-6b860300-78b1-11e9-9d03-d3d9076db5c9.png)
Terimakasih sudah *open issue*, script sudah diperbaiki.
 Jika masalah sudah selesai tolong *reply* **comment** ini, agar saya bisa *close issue*, sekali lagi terimakasih atas kerja samanya :)

**Comment by nikotidar** [comment]
Hai ardzz, betul sebelumnya gue pakai IP Indonesia. Nanti akan gue coba lagi, makasih ya! Keep it up, dude!

**Comment by ardzz** [comment]
Okeee

**Comment by nikotidar** [comment]
Hi! Masih error nih, gue udah pake IP Indonesia (Smartfren)

![Screenshot](https://i.ibb.co/PC4LSx9/Screen-Shot-2019-05-17-at-3-34-54-PM.png "Screenshot")

**Comment by ardzz** [comment]
```
Tested on
OS : Ubuntu 16.04.6 LTS x86_64
PHP : 
PHP 7.0.33-0ubuntu0.16.04.4 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0ubuntu0.16.04.4, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```
Sebelumnya baru aku coba dilokal sih.

**Comment by siikuder** [comment]
Pakai IP mana pun bisa diakses spotify mas, kalo harus ip indo doang, region lain gimana tu aksesnya 😢 coba dibuka PR nya 👍

**Comment by ardzz** [comment]
sudah, makasih ya hihi
